//! Compiling a project's blocks into Rust.
//!
//! The VM walks a `Value` tree and matches on a `Step` every time a block
//! runs. This emits the same program as Rust source instead: an expression
//! becomes an expression, a variable read becomes a call rather than a hash
//! lookup, and a strand becomes a function. Built with the same no-Cargo
//! `rustc` pipeline the scripts use (`crate::script`), a game's logic ends up
//! as native code beside them.
//!
//! The rule the whole thing has to keep is that a compiled program and the VM
//! ask the world for exactly the same things in exactly the same order -
//! including the mistakes, since a bad slot reports itself once and stands a
//! zero in its place. `blockloom-core/tests/codegen.rs` is that rule: it runs
//! a project both ways and compares, line for line, what each one asked for.
//!
//! Anything that reads the world or the clock is a question for the host:
//! sensing reporters, but also `random` and `current time`, so one run of a
//! game has one source of both rather than two that disagree.
//!
//! A strand can be suspended, so it can't be a straight run of Rust: it comes
//! out as a `match` over the program counter, over the very same flattened
//! program the VM steps. Straight-line blocks are fused into one arm, and
//! every point the VM can give the frame back - a `wait`, a `glide`, each
//! iteration of a loop - is an arm of its own that picks up where it left
//! off. Loop nesting is known here rather than at run time, so a `repeat`
//! keeps its tally in a flat slot and a `break` is a jump, where the VM
//! needs a frame stack.
//!
//! The one place the two deliberately part company is the VM's per-tick step
//! budget, which a compiled strand has no counter for. Every back edge is a
//! loop's, and every loop yields, so a compiled strand can't spin - the
//! budget only ever catches a strand of ten thousand straight-line blocks,
//! and paying for a counter on every block to match it there would cost the
//! whole point of compiling.
//!
//! What compiles so far is everything but custom blocks, which are
//! [`Unsupported`] - that refuses the project rather than emitting half of
//! it, so a build can fall back to the VM knowing exactly why.

// Half of this is only ever used by the programs it is pasted into.
#[allow(dead_code)]
mod runtime;

pub use runtime::{Act, Entry, Host, R, State, Status, Val};

use crate::blocks::InstructionKind;
use crate::project::Project;
use crate::value::{Op, Value};
use crate::vm::{Action, LoopKind, Step, compile as compile_program};
use std::collections::{BTreeSet, HashMap};

/// The support code every generated program is built on, pasted in whole -
/// there is no Cargo behind the compile, so there is nothing to depend on.
const RUNTIME_SOURCE: &str = include_str!("runtime.rs");

/// A block this doesn't compile yet. Naming it is the point: a build that
/// falls back to the VM says which block sent it there.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Unsupported {
    pub what: String,
}

impl Unsupported {
    fn new(what: impl Into<String>) -> Self {
        Self { what: what.into() }
    }
}

impl std::fmt::Display for Unsupported {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} can't be compiled yet", self.what)
    }
}

type Emit<T> = Result<T, Unsupported>;

/// Compiles every actor's canvas into one Rust source file, or names the
/// first block that stopped it.
pub fn compile(project: &Project) -> Emit<String> {
    let mut entries = Vec::new();
    let mut bodies = String::new();

    for actor in &project.actors {
        let program = compile_program(&actor.graph);
        if !program.blocks.is_empty() {
            return Err(Unsupported::new("a custom block"));
        }
        for entry in &program.entries {
            let name = format!("strand_{}", entries.len());
            let (body, counters) = emit_strand(&name, &actor.id, &program.steps, entry.pc)?;
            bodies.push_str(&body);
            entries.push(format!(
                "    Entry {{ actor: {}, strand: {}, trigger: {}, detail: {}, \
                 start: {}, counters: {counters}, run: {name} }},",
                literal(&actor.id),
                literal(&entry.strand_id),
                literal(trigger_name(&entry.trigger)),
                literal(&trigger_detail(&entry.trigger)),
                entry.pc,
            ));
        }
    }

    Ok(format!(
        "// Generated by Blockloom from {}. Rebuilt on every build; don't edit.\n\
         #![allow(unused, clippy::all)]\n\n\
         {RUNTIME_SOURCE}\n\
         pub static ENTRIES: &[Entry] = &[\n{}\n];\n\n{bodies}",
        literal(&project.name),
        entries.join("\n")
    ))
}

/// What `trigger`'s [`Entry`] says, in the two halves the runtime matches on.
fn trigger_name(trigger: &crate::vm::Trigger) -> &'static str {
    use crate::vm::Trigger;
    match trigger {
        Trigger::Started => "Started",
        Trigger::KeyPressed(_) => "Key",
        Trigger::Clicked => "Clicked",
        Trigger::Collision { .. } => "Collision",
        Trigger::Message(_) => "Message",
    }
}

fn trigger_detail(trigger: &crate::vm::Trigger) -> String {
    use crate::vm::Trigger;
    match trigger {
        Trigger::KeyPressed(key) => key.clone(),
        Trigger::Collision { with } => with.clone(),
        Trigger::Message(name) => name.clone(),
        Trigger::Started | Trigger::Clicked => String::new(),
    }
}

/// How far into a generated function an arm's own statements sit.
const PAD: &str = "                ";

/// One strand, from its entry point to the `End` that closes it, as a state
/// machine. Answers the source and how many `repeat` counters a run of it
/// needs, which is what the entry table carries.
fn emit_strand(name: &str, actor: &str, steps: &[Step], start: usize) -> Emit<(String, usize)> {
    let Some(end) = (start..steps.len()).find(|&pc| matches!(steps[pc], Step::End)) else {
        // Every strand is emitted body-then-`End`, so this can't happen; an
        // empty function is still better than a panic if it ever does.
        return Ok((empty_strand(name, actor), 0));
    };
    let plan = Plan::of(steps, start, end);

    let mut arms = String::new();
    for (index, &leader) in plan.leaders.iter().enumerate() {
        let next = plan.leaders.get(index + 1).copied().unwrap_or(end + 1);
        let mut body = String::new();
        let mut pc = leader;
        let mut falls_through = true;
        while pc < next {
            body.push_str(&emit_step(&plan, steps, pc)?);
            // Only a plain action leaves the program counter to the arm.
            if !matches!(steps[pc], Step::Action(_)) {
                falls_through = false;
                break;
            }
            pc += 1;
        }
        if falls_through {
            body.push_str(&format!("{PAD}s.pc = {next};\n"));
        }
        arms.push_str(&format!(
            "            {leader} => {{\n{body}            }}\n"
        ));
    }

    let source = format!(
        "fn {name}(h: &mut dyn Host, s: &mut State) {{\n    \
         const ME: &str = {};\n    \
         if !s.resume() {{\n        return;\n    }}\n    \
         loop {{\n        match s.pc {{\n{arms}            \
         _ => {{\n                s.finish();\n                return;\n            }}\n        \
         }}\n    }}\n}}\n\n",
        literal(actor)
    );
    Ok((source, plan.counters.len()))
}

fn empty_strand(name: &str, actor: &str) -> String {
    format!(
        "fn {name}(h: &mut dyn Host, s: &mut State) {{\n    \
         const ME: &str = {};\n    s.finish();\n}}\n\n",
        literal(actor)
    )
}

/// What the emitter works out about a strand before writing any of it: where
/// each arm begins, which loop a `break` leaves, and which slot a `repeat`
/// counts down in.
struct Plan {
    /// Every step an arm starts at, in order: the entry, both sides of a
    /// branch, and every point the strand can be resumed at.
    leaders: Vec<usize>,
    /// Step index -> the `LoopEnd` of the loop around it. The VM finds this
    /// on its frame stack; here it's a fact about the source.
    enclosing: HashMap<usize, usize>,
    /// `LoopBegin` index -> its counter slot. `repeat` only; the other two
    /// kinds have nothing to remember.
    counters: HashMap<usize, usize>,
}

impl Plan {
    fn of(steps: &[Step], start: usize, end: usize) -> Self {
        let mut leaders = BTreeSet::from([start]);
        let mut enclosing = HashMap::new();
        let mut counters = HashMap::new();
        let mut open: Vec<usize> = Vec::new();

        for (pc, step) in steps.iter().enumerate().take(end + 1).skip(start) {
            match step {
                Step::Jump { to } | Step::JumpUnless { to, .. } => {
                    leaders.extend([*to, pc + 1]);
                }
                Step::LoopBegin { kind, end: tail } => {
                    // The head is a jump target of its own: `forever` and
                    // `while` bounce off it to decide on another go round.
                    leaders.extend([pc, pc + 1, tail + 1]);
                    if matches!(kind, LoopKind::Repeat(_)) {
                        counters.insert(pc, counters.len());
                    }
                    open.push(*tail);
                }
                Step::LoopEnd { begin } => {
                    // The back edge is where a loop yields, and `continue`
                    // jumps straight at it.
                    leaders.extend([pc, *begin, begin + 1, pc + 1]);
                    open.pop();
                }
                // Each of these hands the frame back, or can be jumped past.
                Step::Wait(_)
                | Step::Glide { .. }
                | Step::Break
                | Step::Continue
                | Step::Return(_)
                | Step::StopAll => {
                    leaders.insert(pc + 1);
                }
                // Re-checked from the top every frame until it holds, so it
                // is its own resume point.
                Step::WaitUntil(_) => {
                    leaders.extend([pc, pc + 1]);
                }
                Step::Action(_) | Step::End | Step::Call { .. } => {}
            }
            if let Some(&tail) = open.last() {
                enclosing.insert(pc, tail);
            }
        }

        Self {
            leaders: leaders
                .into_iter()
                .filter(|&pc| pc >= start && pc <= end)
                .collect(),
            enclosing,
            counters,
        }
    }
}

/// One step, as the statements that carry it out and say where to go next.
/// Everything but an action sets `s.pc` itself, and so ends its arm.
fn emit_step(plan: &Plan, steps: &[Step], pc: usize) -> Emit<String> {
    let next = pc + 1;
    Ok(match &steps[pc] {
        Step::Action(action) => nested(&emit_action(action)?),
        Step::Jump { to } => format!("{PAD}s.pc = {to};\n"),
        Step::JumpUnless { condition, to } => format!(
            "{PAD}let holds = {};\n{PAD}s.pc = if holds {{ {next} }} else {{ {to} }};\n",
            boolean(condition)?
        ),
        Step::LoopBegin { kind, end } => match kind {
            // Counted once, on the way in - the back edge lands past the head.
            LoopKind::Repeat(count) => format!(
                "{PAD}let n = {}.round() as i64;\n\
                 {PAD}if n <= 0 {{\n{PAD}    s.pc = {};\n{PAD}}} else {{\n\
                 {PAD}    s.enter_repeat({}, n);\n{PAD}    s.pc = {next};\n{PAD}}}\n",
                number_f64(count)?,
                end + 1,
                plan.counters[&pc]
            ),
            LoopKind::Forever => format!("{PAD}s.pc = {next};\n"),
            // Re-checked here every time round, which is what the back edge
            // pointing at the head is for.
            LoopKind::While(condition) => format!(
                "{PAD}let holds = {};\n{PAD}s.pc = if holds {{ {next} }} else {{ {} }};\n",
                boolean(condition)?,
                end + 1
            ),
        },
        // The per-iteration yield, and the only one a `forever` ever reaches.
        Step::LoopEnd { begin } => match plan.counters.get(begin) {
            Some(slot) => format!(
                "{PAD}let left = s.next_iteration({slot});\n\
                 {PAD}s.pc = if left <= 0 {{ {next} }} else {{ {} }};\n{PAD}return;\n",
                begin + 1
            ),
            None => format!("{PAD}s.pc = {begin};\n{PAD}return;\n"),
        },
        // Outside a loop both are no-ops, exactly as the VM leaves them.
        Step::Break => match plan.enclosing.get(&pc) {
            Some(tail) => format!("{PAD}s.pc = {};\n", tail + 1),
            None => format!("{PAD}s.pc = {next};\n"),
        },
        Step::Continue => match plan.enclosing.get(&pc) {
            Some(tail) => format!("{PAD}s.pc = {tail};\n"),
            None => format!("{PAD}s.pc = {next};\n"),
        },
        // A zero-second wait doesn't give the frame back, so a `wait 0` stays
        // the way to do nothing rather than a way to yield.
        Step::Wait(duration) => format!(
            "{PAD}let seconds = {}.max(0.0);\n{PAD}s.pc = {next};\n\
             {PAD}if seconds > 0.0 {{\n{PAD}    s.sleep(seconds);\n{PAD}    return;\n{PAD}}}\n",
            number_f64(duration)?
        ),
        Step::WaitUntil(condition) => format!(
            "{PAD}let holds = {};\n{PAD}if !holds {{\n{PAD}    return;\n{PAD}}}\n\
             {PAD}s.pc = {next};\n",
            boolean(condition)?
        ),
        // The slide is the host's to draw; the strand just sleeps for as long.
        Step::Glide { seconds, target } => format!(
            "{PAD}let seconds = {}.max(0.0);\n{PAD}let target = {};\n\
             {PAD}h.act(ME, Act::Glide {{ seconds: seconds as f32, target }});\n\
             {PAD}s.pc = {next};\n\
             {PAD}if seconds > 0.0 {{\n{PAD}    s.sleep(seconds);\n{PAD}    return;\n{PAD}}}\n",
            number_f64(seconds)?,
            vec3(target)?
        ),
        // With no call to return through, a `return` ends the strand - but
        // its slot is still evaluated, so a bad one still reports itself.
        Step::Return(value) => format!(
            "{PAD}let _ = {};\n{PAD}s.finish();\n{PAD}return;\n",
            evaluated(value)?
        ),
        Step::StopAll => format!("{PAD}s.stopping = true;\n{PAD}s.finish();\n{PAD}return;\n"),
        Step::End => format!("{PAD}s.finish();\n{PAD}return;\n"),
        Step::Call { .. } => return Err(Unsupported::new("a custom block")),
    })
}

/// Lines written for a bare statement, moved in to sit inside an arm.
fn nested(lines: &str) -> String {
    lines
        .lines()
        .map(|line| format!("            {line}\n"))
        .collect()
}

fn emit_action(action: &Action) -> Emit<String> {
    let line = match action {
        Action::Move(steps) => reading(number(steps)?, "Act::Move { steps: slot }"),
        Action::GoTo(target) => reading(vec3(target)?, "Act::GoTo { position: slot }"),
        Action::ChangePosition { axis, by } => reading(
            number(by)?,
            &format!("Act::ChangePosition {{ axis: {}, by: slot }}", axis.index()),
        ),
        Action::Turn { axis, degrees } => reading(
            number(degrees)?,
            &format!("Act::Turn {{ axis: {}, degrees: slot }}", axis.index()),
        ),
        Action::SetRotation { axis, degrees } => reading(
            number(degrees)?,
            &format!(
                "Act::SetRotation {{ axis: {}, degrees: slot }}",
                axis.index()
            ),
        ),
        Action::PointTowards(target) => act(format!(
            "Act::PointTowards {{ target: {} }}",
            literal(target)
        )),
        Action::SetScale(factor) => reading(number(factor)?, "Act::SetScale { factor: slot }"),
        Action::SetBody(body) => act(format!("Act::SetBody {{ body: {} }}", name_of(body))),
        Action::ApplyImpulse(vector) => {
            reading(vec3(vector)?, "Act::ApplyImpulse { impulse: slot }")
        }
        Action::SetVelocity(vector) => {
            reading(vec3(vector)?, "Act::SetVelocity { velocity: slot }")
        }
        Action::SetGravity(vector) => reading(vec3(vector)?, "Act::SetGravity { gravity: slot }"),
        Action::SetDensity(density) => {
            reading(number(density)?, "Act::SetDensity { density: slot }")
        }
        Action::SetMass(mass) => reading(number(mass)?, "Act::SetMass { mass: slot }"),
        Action::Say(value) => reading(text(value)?, "Act::Say { text: slot }"),
        Action::SetVisible(visible) => act(format!("Act::SetVisible {{ visible: {visible} }}")),
        Action::SetColor(color) => reading(text(color)?, "Act::SetColor { color: slot }"),
        Action::SetComponentField {
            component,
            field,
            value,
        } => reading(
            evaluated(value)?,
            &format!(
                "Act::SetComponentField {{ component: {}, field: {}, value: slot }}",
                literal(component.trim()),
                literal(field.trim())
            ),
        ),
        Action::SetCameraView(view) => {
            act(format!("Act::SetCameraView {{ view: {} }}", name_of(view)))
        }
        Action::AttachComponent(component) => act(format!(
            "Act::AttachComponent {{ component: {} }}",
            literal(component)
        )),
        Action::DetachComponent(component) => act(format!(
            "Act::DetachComponent {{ component: {} }}",
            literal(component)
        )),
        Action::Broadcast(name) => act(format!(
            "Act::Broadcast {{ name: {} }}",
            literal(name.trim())
        )),
        // A variable write isn't an effect: it is the host's own state, so it
        // goes through the host rather than through `Act`.
        Action::SetVariable { name, value } => format!(
            "    let value = {};\n    h.set_variable(ME, {}, value);\n",
            evaluated(value)?,
            literal(name)
        ),
        // The delta and the current value are both numbers-or-zero, and
        // neither reports a non-numeric one, exactly as in Scratch.
        Action::ChangeVariable { name, value } => format!(
            "    let by = {};\n    \
             let now = h.variable(ME, {name_literal}).as_number().unwrap_or(0.0);\n    \
             h.set_variable(ME, {name_literal}, Val::Num(now + by));\n",
            number_f64(value)?,
            name_literal = literal(name)
        ),
    };
    Ok(line)
}

/// One emitted line, handing the host something to do.
fn act(built: String) -> String {
    format!("    h.act(ME, {built});\n")
}

/// The same, for an act with a slot in it. The slot is read into a `let`
/// first: building the act borrows the host and so does reading a slot, and
/// one expression can't do both.
fn reading(reader: String, built: &str) -> String {
    format!("    let slot = {reader};\n    h.act(ME, {built});\n")
}

/// An enum variant as a string literal holding its Rust name, which is what
/// the host maps back. Only fieldless enums travel this way, so `Debug` is
/// the name and nothing else.
fn name_of(value: &impl std::fmt::Debug) -> String {
    literal(&format!("{value:?}"))
}

/// Reading a slot borrows the host, and so does the expression in it - a
/// sensing block asks the host a question of its own. So every read is a
/// block that works the expression out into a local first, which nests as
/// deeply as the blocks do.
fn read_with(reader: &str, value: &Value) -> Emit<String> {
    Ok(format!(
        "{{ let v = {}; {reader}(h, ME, v) }}",
        value_expr(value)?
    ))
}

fn number(value: &Value) -> Emit<String> {
    read_with("number", value)
}

fn number_f64(value: &Value) -> Emit<String> {
    read_with("number_f64", value)
}

fn text(value: &Value) -> Emit<String> {
    read_with("text", value)
}

fn evaluated(value: &Value) -> Emit<String> {
    read_with("evaluated", value)
}

fn boolean(value: &Value) -> Emit<String> {
    read_with("boolean", value)
}

fn vec3(values: &[Value; 3]) -> Emit<String> {
    Ok(format!(
        "{{ let x = {}; let y = {}; let z = {}; vec3(h, ME, [x, y, z]) }}",
        value_expr(&values[0])?,
        value_expr(&values[1])?,
        value_expr(&values[2])?
    ))
}

/// One value slot, as an expression of type `R`.
fn value_expr(value: &Value) -> Emit<String> {
    match value {
        Value::Number { value } => Ok(format!("Ok(Val::Num({}))", float(*value))),
        Value::Text { value } => Ok(format!("Ok(Val::Text({}.to_string()))", literal(value))),
        Value::Bool => Ok("Ok(Val::Bool(false))".to_string()),
        Value::Var { name } => Ok(format!("Ok(h.variable(ME, {}))", literal(name))),
        Value::Param { .. } => Err(Unsupported::new("a custom block's input")),
        Value::Call { .. } => Err(Unsupported::new("a custom block")),
        Value::Op { op, args, .. } => op_expr(op, args),
    }
}

fn op_expr(op: &Op, args: &[Value]) -> Emit<String> {
    let arg = |index: usize| -> Emit<String> {
        args.get(index)
            .ok_or_else(|| Unsupported::new(format!("`{}` with a missing slot", op.name())))
            .and_then(value_expr)
    };
    let call = |name: &str, count: usize| -> Emit<String> {
        let mut parts = Vec::with_capacity(count);
        for index in 0..count {
            parts.push(arg(index)?);
        }
        Ok(format!("{name}({})", parts.join(", ")))
    };

    match op {
        Op::Add => call("add", 2),
        Op::Sub => call("sub", 2),
        Op::Mul => call("mul", 2),
        Op::Div => call("div", 2),
        Op::Mod => call("modulo", 2),
        Op::Round => call("round", 1),
        Op::Math => call("math", 2),
        Op::Length => call("length", 1),
        Op::IndexOf => call("index_of", 2),
        Op::LastIndexOf => call("last_index_of", 2),
        Op::LetterOf => call("letter_of", 2),
        Op::Case => call("case", 2),
        Op::Eq => call("eq", 2),
        Op::Neq => call("neq", 2),
        Op::Gt => call("gt", 2),
        Op::Lt => call("lt", 2),
        Op::Gte => call("gte", 2),
        Op::Lte => call("lte", 2),
        Op::Not => call("not", 1),
        Op::True => Ok("Ok(Val::Bool(true))".to_string()),
        Op::False => Ok("Ok(Val::Bool(false))".to_string()),
        Op::NewLine => Ok("Ok(Val::Text(\"\\n\".to_string()))".to_string()),
        Op::Tab => Ok("Ok(Val::Text(\"\\t\".to_string()))".to_string()),
        // The second operand stays unevaluated: `false and <a bad slot>`
        // reports nothing, and that is observable.
        Op::And => Ok(format!("and({}, || {})", arg(0)?, arg(1)?)),
        Op::Or => Ok(format!("or({}, || {})", arg(0)?, arg(1)?)),
        // Join is the one built-in that takes however many it was given.
        Op::Join => {
            let mut parts = Vec::with_capacity(args.len());
            for value in args {
                parts.push(value_expr(value)?);
            }
            Ok(format!("join(vec![{}])", parts.join(", ")))
        }
        // The world and the clock are the host's to answer, so that one run
        // of a game has one of each rather than two that disagree.
        Op::Random => Ok(format!(
            "{{ let a = vec![{}, {}]; sense(h, ME, \"Random\", a) }}",
            arg(0)?,
            arg(1)?
        )),
        Op::CurrentTime => Ok(format!(
            "{{ let a = vec![{}]; sense(h, ME, \"CurrentTime\", a) }}",
            arg(0)?
        )),
        Op::Ext(name) => {
            let mut parts = Vec::with_capacity(args.len());
            for value in args {
                parts.push(value_expr(value)?);
            }
            Ok(format!(
                "{{ let a = vec![{}]; sense(h, ME, {}, a) }}",
                parts.join(", "),
                literal(name)
            ))
        }
    }
}

/// A Rust string literal holding exactly `text`.
fn literal(text: &str) -> String {
    format!("{text:?}")
}

/// A Rust `f64` literal. `{:?}` keeps every digit that matters but spells the
/// three values that aren't numbers in a way rustc won't take.
fn float(value: f64) -> String {
    if value.is_nan() {
        return "f64::NAN".to_string();
    }
    if value.is_infinite() {
        return if value > 0.0 {
            "f64::INFINITY".to_string()
        } else {
            "f64::NEG_INFINITY".to_string()
        };
    }
    format!("{value:?}f64")
}

/// Whether this block is one [`compile`] could handle, for a palette that
/// wants to say so. Cheaper than compiling, and used by the tests to keep the
/// two lists honest.
pub fn supports(kind: &InstructionKind) -> bool {
    !matches!(kind, InstructionKind::CallBlock { .. })
}

#[cfg(test)]
mod tests;
