// Lucide icons, and the one each block type wears. Registered with blockstitch
// at startup so every `icon="..."` string in its own chrome resolves too.
import type { Component } from 'vue';
import {
  ArrowRight,
  Asterisk,
  Blocks,
  Boxes,
  Camera,
  Circle,
  CircleDot,
  Clock,
  Cloud,
  Copy,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  Crosshair,
  Eye,
  Flag,
  GitBranch,
  GitFork,
  Hand,
  Image,
  Infinity as InfinityIcon,
  Keyboard,
  Layers,
  LayoutPanelTop,
  Link,
  ListChecks,
  Lock,
  LogOut,
  Maximize,
  MessageSquare,
  MousePointerClick,
  Move,
  Move3d,
  Octagon,
  Palette,
  Pause,
  PanelsTopLeft,
  Play,
  Plus,
  Radio,
  Redo2,
  Repeat,
  RotateCw,
  Save,
  Scale,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareDashed,
  SquareMousePointer,
  Type,
  Sun,
  Moon,
  Target,
  TextCursorInput,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Undo2,
  Upload,
  Download,
  Video,
  Weight,
  Wind,
  X,
  Zap,
} from 'lucide-vue-next';
import type { InstructionType } from './types';

export const ICONS: Record<string, Component> = {
  flag: Flag,
  keyboard: Keyboard,
  'mouse-pointer-click': MousePointerClick,
  crosshair: Crosshair,
  radio: Radio,
  blocks: Blocks,
  camera: Camera,
  'panels-top-left': PanelsTopLeft,
  move: Move,
  'move-3d': Move3d,
  target: Target,
  wind: Wind,
  'rotate-cw': RotateCw,
  scale: Scale,
  maximize: Maximize,
  boxes: Boxes,
  zap: Zap,
  'trending-up': TrendingUp,
  cloud: Cloud,
  'message-square': MessageSquare,
  eye: Eye,
  palette: Palette,
  clock: Clock,
  hand: Hand,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  repeat: Repeat,
  infinity: InfinityIcon,
  'skip-forward': SkipForward,
  'sliders-horizontal': SlidersHorizontal,
  'square-mouse-pointer': SquareMousePointer,
  'text-cursor-input': TextCursorInput,
  'toggle-left': ToggleLeft,
  type: Type,
  image: Image,
  'log-out': LogOut,
  octagon: Octagon,
  asterisk: Asterisk,
  'corner-down-right': CornerDownRight,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'arrow-right': ArrowRight,
  layers: Layers,
  'layout-panel-top': LayoutPanelTop,
  'list-checks': ListChecks,
  link: Link,
  lock: Lock,
  copy: Copy,
  sparkles: Sparkles,
  square: Square,
  'square-dashed': SquareDashed,
  circle: Circle,
  'circle-dot': CircleDot,
  weight: Weight,
  play: Play,
  pause: Pause,
  plus: Plus,
  trash: Trash2,
  save: Save,
  undo: Undo2,
  redo: Redo2,
  upload: Upload,
  download: Download,
  video: Video,
  sun: Sun,
  moon: Moon,
  x: X,
};

export const BLOCK_ICONS: Record<InstructionType, string> = {
  WhenStarted: 'flag',
  WhenKeyPressed: 'keyboard',
  WhenClicked: 'mouse-pointer-click',
  WhenCollision: 'crosshair',
  WhenMessage: 'radio',
  WhenCloned: 'copy',
  WhenUiClicked: 'square-mouse-pointer',
  WhenUiChanged: 'sliders-horizontal',
  BlockHeader: 'blocks',
  Move: 'arrow-right',
  GoTo: 'move',
  ChangePosition: 'move-3d',
  Glide: 'wind',
  Turn: 'rotate-cw',
  SetRotation: 'rotate-cw',
  PointTowards: 'target',
  SetScale: 'maximize',
  SetBody: 'boxes',
  ApplyImpulse: 'zap',
  SetVelocity: 'trending-up',
  SetGravity: 'cloud',
  SetDensity: 'weight',
  SetMass: 'weight',
  Say: 'message-square',
  SetVisible: 'eye',
  SetColor: 'palette',
  SetComponentField: 'panels-top-left',
  SetCameraView: 'camera',
  SetCameraPitch: 'video',
  AttachComponent: 'plus',
  DetachComponent: 'x',
  SetParent: 'link',
  CreateClone: 'copy',
  CreateActor: 'sparkles',
  DeleteActor: 'trash',
  Wait: 'clock',
  WaitUntil: 'hand',
  If: 'git-branch',
  IfElse: 'git-fork',
  Repeat: 'repeat',
  Forever: 'infinity',
  While: 'repeat',
  EscapeLoop: 'log-out',
  ContinueLoop: 'skip-forward',
  Broadcast: 'radio',
  StopAll: 'octagon',
  SetMouseLocked: 'lock',
  ShowPanel: 'layout-panel-top',
  ShowLabel: 'type',
  ShowButton: 'square-mouse-pointer',
  ShowImage: 'image',
  ShowInput: 'text-cursor-input',
  ShowSlider: 'sliders-horizontal',
  ShowToggle: 'toggle-left',
  SetUiProp: 'list-checks',
  HideElement: 'eye',
  HideAllUi: 'eye',
  DeleteElement: 'trash',
  PauseGame: 'pause',
  ResumeGame: 'play',
  SetVariable: 'asterisk',
  ChangeVariable: 'trending-up',
  CallBlock: 'blocks',
  Return: 'corner-down-right',
};

/** Human label for a block, for the palette's own tooltips and menus. */
export const BLOCK_LABELS: Record<InstructionType, string> = {
  WhenStarted: 'when the project starts',
  WhenKeyPressed: 'when a key is pressed',
  WhenClicked: 'when I am clicked',
  WhenCollision: 'when I touch',
  WhenMessage: 'when I get a message',
  WhenCloned: 'when I start as a clone',
  WhenUiClicked: 'when an element is clicked',
  WhenUiChanged: 'when an input is changed',
  BlockHeader: 'block definition',
  Move: 'move forward',
  GoTo: 'go to',
  ChangePosition: 'change position',
  Glide: 'glide to',
  Turn: 'turn',
  SetRotation: 'point in direction',
  PointTowards: 'point towards',
  SetScale: 'set size',
  SetBody: 'set body',
  ApplyImpulse: 'push',
  SetVelocity: 'set velocity',
  SetGravity: 'set gravity',
  SetDensity: 'set density',
  SetMass: 'set mass',
  Say: 'say',
  SetVisible: 'show or hide',
  SetColor: 'set color',
  SetComponentField: 'set a component field',
  SetCameraView: 'set my camera view',
  SetCameraPitch: 'set camera pitch',
  AttachComponent: 'attach a component',
  DetachComponent: 'detach a component',
  SetParent: 'attach me to an actor',
  CreateClone: 'create a clone',
  CreateActor: 'create an actor',
  DeleteActor: 'delete an actor',
  Wait: 'wait',
  WaitUntil: 'wait until',
  If: 'if',
  IfElse: 'if else',
  Repeat: 'repeat',
  Forever: 'forever',
  While: 'while',
  EscapeLoop: 'break out of the loop',
  ContinueLoop: 'next loop iteration',
  Broadcast: 'broadcast',
  StopAll: 'stop everything',
  SetMouseLocked: 'lock or unlock the mouse',
  ShowPanel: 'show a panel',
  ShowLabel: 'show a label',
  ShowButton: 'show a button',
  ShowImage: 'show an image',
  ShowInput: 'show a text input',
  ShowSlider: 'show a slider',
  ShowToggle: 'show a toggle',
  SetUiProp: 'set an element property',
  HideElement: 'hide an element',
  HideAllUi: 'hide all ui',
  DeleteElement: 'delete an element',
  PauseGame: 'pause the game',
  ResumeGame: 'resume the game',
  SetVariable: 'set a variable',
  ChangeVariable: 'change a variable',
  CallBlock: 'my block',
  Return: 'return',
};
