// Lucide icons, and the one each block type wears. Registered with blockstitch
// at startup so every `icon="..."` string in its own chrome resolves too.
import type { Component } from 'vue';
import {
  ArrowRight,
  Asterisk,
  Blocks,
  Boxes,
  Camera,
  Circle,
  CircleDot,
  Clock,
  Cloud,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  Crosshair,
  Eye,
  Flag,
  GitBranch,
  GitFork,
  Hand,
  Infinity as InfinityIcon,
  Keyboard,
  Layers,
  LogOut,
  Maximize,
  MessageSquare,
  MousePointerClick,
  Move,
  Move3d,
  Octagon,
  Palette,
  Pause,
  PanelsTopLeft,
  Play,
  Plus,
  Radio,
  Redo2,
  Repeat,
  RotateCw,
  Save,
  Scale,
  SkipForward,
  Square,
  SquareDashed,
  Sun,
  Moon,
  Target,
  Trash2,
  TrendingUp,
  Undo2,
  Upload,
  Download,
  Wind,
  X,
  Zap,
} from 'lucide-vue-next';
import type { InstructionType } from './types';

export const ICONS: Record<string, Component> = {
  flag: Flag,
  keyboard: Keyboard,
  'mouse-pointer-click': MousePointerClick,
  crosshair: Crosshair,
  radio: Radio,
  blocks: Blocks,
  camera: Camera,
  'panels-top-left': PanelsTopLeft,
  move: Move,
  'move-3d': Move3d,
  target: Target,
  wind: Wind,
  'rotate-cw': RotateCw,
  scale: Scale,
  maximize: Maximize,
  boxes: Boxes,
  zap: Zap,
  'trending-up': TrendingUp,
  cloud: Cloud,
  'message-square': MessageSquare,
  eye: Eye,
  palette: Palette,
  clock: Clock,
  hand: Hand,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  repeat: Repeat,
  infinity: InfinityIcon,
  'skip-forward': SkipForward,
  'log-out': LogOut,
  octagon: Octagon,
  asterisk: Asterisk,
  'corner-down-right': CornerDownRight,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'arrow-right': ArrowRight,
  layers: Layers,
  square: Square,
  'square-dashed': SquareDashed,
  circle: Circle,
  'circle-dot': CircleDot,
  play: Play,
  pause: Pause,
  plus: Plus,
  trash: Trash2,
  save: Save,
  undo: Undo2,
  redo: Redo2,
  upload: Upload,
  download: Download,
  sun: Sun,
  moon: Moon,
  x: X,
};

export const BLOCK_ICONS: Record<InstructionType, string> = {
  WhenStarted: 'flag',
  WhenKeyPressed: 'keyboard',
  WhenClicked: 'mouse-pointer-click',
  WhenCollision: 'crosshair',
  WhenMessage: 'radio',
  BlockHeader: 'blocks',
  Move: 'arrow-right',
  GoTo: 'move',
  ChangePosition: 'move-3d',
  Glide: 'wind',
  Turn: 'rotate-cw',
  SetRotation: 'rotate-cw',
  PointTowards: 'target',
  SetScale: 'maximize',
  SetBody: 'boxes',
  ApplyImpulse: 'zap',
  SetVelocity: 'trending-up',
  SetGravity: 'cloud',
  Say: 'message-square',
  SetVisible: 'eye',
  SetColor: 'palette',
  SetComponentField: 'panels-top-left',
  SetCameraView: 'camera',
  AttachComponent: 'plus',
  DetachComponent: 'x',
  Wait: 'clock',
  WaitUntil: 'hand',
  If: 'git-branch',
  IfElse: 'git-fork',
  Repeat: 'repeat',
  Forever: 'infinity',
  While: 'repeat',
  EscapeLoop: 'log-out',
  ContinueLoop: 'skip-forward',
  Broadcast: 'radio',
  StopAll: 'octagon',
  SetVariable: 'asterisk',
  ChangeVariable: 'trending-up',
  CallBlock: 'blocks',
  Return: 'corner-down-right',
};

/** Human label for a block, for the palette's own tooltips and menus. */
export const BLOCK_LABELS: Record<InstructionType, string> = {
  WhenStarted: 'when the project starts',
  WhenKeyPressed: 'when a key is pressed',
  WhenClicked: 'when I am clicked',
  WhenCollision: 'when I touch',
  WhenMessage: 'when I get a message',
  BlockHeader: 'block definition',
  Move: 'move forward',
  GoTo: 'go to',
  ChangePosition: 'change position',
  Glide: 'glide to',
  Turn: 'turn',
  SetRotation: 'point in direction',
  PointTowards: 'point towards',
  SetScale: 'set size',
  SetBody: 'set body',
  ApplyImpulse: 'push',
  SetVelocity: 'set velocity',
  SetGravity: 'set gravity',
  Say: 'say',
  SetVisible: 'show or hide',
  SetColor: 'set color',
  SetComponentField: 'set a component field',
  SetCameraView: 'set my camera view',
  AttachComponent: 'attach a component',
  DetachComponent: 'detach a component',
  Wait: 'wait',
  WaitUntil: 'wait until',
  If: 'if',
  IfElse: 'if else',
  Repeat: 'repeat',
  Forever: 'forever',
  While: 'while',
  EscapeLoop: 'break out of the loop',
  ContinueLoop: 'next loop iteration',
  Broadcast: 'broadcast',
  StopAll: 'stop everything',
  SetVariable: 'set a variable',
  ChangeVariable: 'change a variable',
  CallBlock: 'my block',
  Return: 'return',
};
