name: Build packages

on:
  workflow_call:
    inputs:
      shipping:
        type: boolean
        default: false
      tag:
        type: string
        default: ''

permissions:
  contents: read

jobs:
  platforms:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: linux_gcc_64
          - os: windows-2025-vs2026
            arch: win64_msvc2022_64
          - os: xcode-27
            arch: clang_64
            deployment-target: '27.0'
    uses: ./.github/workflows/build-platform.yml
    with:
      os: ${{ matrix.os }}
      qt-arch: ${{ matrix.arch }}
      deployment-target: ${{ matrix.deployment-target || '' }}
      shipping: ${{ inputs.shipping }}
      tag: ${{ inputs.tag }}
